site_name: ipyvizzu-story
site_url: https://vizzuhq.github.io/ipyvizzu-story/

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu-story
edit_uri: https://github.com/vizzuhq/ipyvizzu-story/edit/main/docs
use_directory_urls: false

theme:
  name: material
  custom_dir: ./overrides
  icon:
    logo: material/home

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
  - mkdocs-jupyter:
      execute: True
      ignore: ["demo/*.ipynb"]
      ignore_h1_titles: True
      include_source: True
  - gen-files:
      scripts:
        - gen_files.py
  - literate-nav

nav:
  - Home: index.md
  - Documentation:
      - docs/index.md
      - docs/installation.md
      - docs/tutorial.md
      - Environments:
          - docs/environments/index.md
          - Jupyter/IPython:
              - docs/environments/jupyter/index.md
              - Jupyter Notebook: docs/environments/jupyter/jupyternotebook.md
              - docs/environments/jupyter/colab.md
              - docs/environments/jupyter/databricks.md
              - DataCamp: docs/environments/jupyter/datacamp.md
              - docs/environments/jupyter/deepnote.md
              - JupyterLab: docs/environments/jupyter/jupyterlab.md
              - JupyterLite: docs/environments/jupyter/jupyterlite.md
              - docs/environments/jupyter/kaggle.md
              - Mercury (mljar): docs/environments/jupyter/mercury.md
              - docs/environments/jupyter/mode.md
              - docs/environments/jupyter/noteable.md
              - Voilà: docs/environments/jupyter/voila.md
              - VSCode: docs/environments/jupyter/vscode.md
          - docs/environments/streamlit.md
          - docs/environments/panel.md
          - docs/environments/python.md
  - Examples:
      - examples/index.md
      - Basic example: examples/basic/basic.ipynb
      - Complex example: examples/complex/complex.ipynb
  - Reference: reference/ipyvizzustory/
